# `arrange` — Row Sorting & Ordering

`arrange` orders DataFrame rows by one or more columns with full support for descending orders (`desc`, `-col`), global `ascending=` overrides, and bracket notation for columns with spaces (`[col name]`).

| Method | Key Params | Purpose |
|---|---|---|
| `.pt.arrange(*cols, ascending=None, na_last=True)` | `*cols`, `ascending`, `na_last` | Sort rows ascending / descending |

---

In [1]:
import sys, os
_src = os.path.abspath(os.path.join(os.getcwd(), '..', '..', 'src'))
if not os.path.exists(_src): _src = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if _src not in sys.path: sys.path.insert(0, _src)

import pytae as pt

penguins = pt.sample_data['penguins']
tips = pt.sample_data['tips']

## 1. `arrange()` — Basic Sorting

By default, `.pt.arrange()` sorts in ascending order.

In [2]:
# Sort ascending by body mass
penguins.pt.arrange("body_mass_g").pt.select("species", "island", "body_mass_g").head(5)

     species     island  body_mass_g
0  Chinstrap      Dream       2700.0
1     Adelie     Biscoe       2850.0
2     Adelie     Biscoe       2850.0
3     Adelie  Torgersen       2900.0
4     Adelie      Dream       2900.0

## 2. Descending Order: `desc` keyword and `-` shorthand

Specify descending order either by appending `desc` or prefixing the column name with `-`.

In [3]:
# Using explicit 'desc'
penguins.pt.arrange("body_mass_g desc").pt.select("species", "island", "body_mass_g").head(5)

  species  island  body_mass_g
0  Gentoo  Biscoe       6300.0
1  Gentoo  Biscoe       6050.0
2  Gentoo  Biscoe       6000.0
3  Gentoo  Biscoe       6000.0
4  Gentoo  Biscoe       5950.0

In [4]:
# Using leading minus '-' shorthand
penguins.pt.arrange("-body_mass_g").pt.select("species", "island", "body_mass_g").head(5)

  species  island  body_mass_g
0  Gentoo  Biscoe       6300.0
1  Gentoo  Biscoe       6050.0
2  Gentoo  Biscoe       6000.0
3  Gentoo  Biscoe       6000.0
4  Gentoo  Biscoe       5950.0

## 3. Multi-Column Sorting

Pass multiple column specifications either as separate arguments or as a comma-separated string.

In [5]:
# Multi-column: species ascending, body_mass_g descending
penguins.pt.arrange("species", "body_mass_g desc").pt.select("species", "island", "body_mass_g").head(6)

  species     island  body_mass_g
0  Adelie     Biscoe       4775.0
1  Adelie     Biscoe       4725.0
2  Adelie  Torgersen       4700.0
3  Adelie  Torgersen       4675.0
4  Adelie      Dream       4650.0
5  Adelie      Dream       4600.0

In [16]:
# Comma-separated string with shorthand minus
penguins.pt.arrange("species, -body_mass_g").pt.select("species", "island", "body_mass_g").head(6)

  species     island  body_mass_g
0  Adelie     Biscoe       4775.0
1  Adelie     Biscoe       4725.0
2  Adelie  Torgersen       4700.0
3  Adelie  Torgersen       4675.0
4  Adelie      Dream       4650.0
5  Adelie      Dream       4600.0

## 4. Column Names with Spaces (`[col name]`)

Columns with spaces are cleanly referenced using square brackets `[col name]`.

In [7]:
# Rename column to include spaces
spaced_penguins = penguins.rename(columns={"bill_length_mm": "bill length mm"})

# Sort by bracketed column name descending
spaced_penguins.pt.arrange("[bill length mm] desc").pt.select("species", "[bill length mm]").head(5)

     species  bill length mm
0     Gentoo            59.6
1  Chinstrap            58.0
2     Gentoo            55.9
3  Chinstrap            55.8
4     Gentoo            55.1

## 5. Functional Style (`pt.arrange`)

Available as standalone functional verb `pt.arrange(df, ...)`:

In [12]:
# Functional arrange
top_tips = pt.arrange(tips, "-tip")
top_tips[["total_bill", "tip", "day"]].head(4)

   total_bill    tip  day
0       50.81  10.00  Sat
1       48.33   9.00  Sat
2       39.42   7.58  Sat
3       48.27   6.73  Sat