# `qry` — Reference

`qry` filters a DataFrame using intuitive keyword arguments, CLI-style string expressions, plain dictionaries, or any combination of the three.

### Calling Styles

`qry` supports multiple flexible calling styles to fit interactive analysis, programmatic pipelines, and column names with spaces:

- **Keyword arguments**: `df.pt.qry(species='Adelie', body_mass_g='> 5000')`
- **String expressions** (matches CLI `-qry` syntax; handles spaces directly): `df.pt.qry("bill length mm > 40, species = 'Adelie'")`
- **Plain dictionaries** (ideal for dynamic keys or columns with spaces): `df.pt.qry({"bill length mm": "> 40", "species": "Adelie"})`
- **Mixed calling**: `df.pt.qry("bill length mm > 40", {"island": "Biscoe"}, species="Gentoo")`
- **Library function**: `pt.qry(df, species='Adelie', body_mass_g='> 5000')`

### Supported Condition Types

| Condition | Example Syntax | Meaning |
|---|---|---|
| Equality | `species='Adelie'` or `"species = Adelie"` | exact match |
| Membership | `species=['Adelie', 'Gentoo']` | in list |
| Tuple membership | `species=('in', ['Adelie', 'Gentoo'])` | in list |
| Exclusion | `sex=('not in', ['Male'])` | not in list |
| Comparison (operator) | `body_mass_g='> 5000'` or `body_mass_g=('>', 5000)` | `>`, `>=`, `<`, `<=`, `==`, `!=` |
| Open interval | `body_mass_g='(3500,4500)'` | `3500 < x < 4500` |
| Half-open interval | `bill_length_mm='[40,50)'` | `40 <= x < 50` |
| Closed interval | `body_mass_g='[3500,4000]'` | `3500 <= x <= 4000` |
| String matching | `species=('startswith', 'Ad')` | `startswith`, `endswith`, `contains`, `regex` |
| Multiple prefixes/suffixes | `species=('startswith', ['Ad', 'Ge'])` | matches any prefix/suffix in list/tuple |
| Null check | `sex=('isna',)` / `sex=('notna',)` | missing / non-missing (unary tuple) |
| Columns with spaces | `"bill length mm > 40"` or `{"bill length mm": "> 40"}` | spaces handled without dict unpacking |
| Same-column bounds | `"mass > 3000, mass < 5000"` or `"mass > 3000", "mass < 5000"` | multiple conditions on same column |

---

In [1]:
import sys, os
_src = os.path.abspath(os.path.join(os.getcwd(), '..', '..', 'src'))
if not os.path.exists(_src): _src = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if _src not in sys.path: sys.path.insert(0, _src)

import pytae as pt

penguins = pt.sample_data['penguins']
tips = pt.sample_data['tips']
titanic = pt.sample_data['titanic']

## Flexible calling styles: kwargs, string expressions, and dictionaries

`qry()` accepts conditions as keyword arguments, string expressions matching the CLI `-qry` syntax, plain dictionaries, or any mix of the three. Both the DataFrame accessor (`df.pt.qry(...)`) and the top-level library verb (`pt.qry(df, ...)`) are supported.

In [2]:
# 1. Keyword arguments — clean and pythonic
(
    penguins
    .pt.qry(species='Adelie', island='Dream')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
30,Adelie,Dream,39.5,16.7,178.0,3250.0,Female
91,Adelie,Dream,41.1,18.1,205.0,4300.0,Male
140,Adelie,Dream,40.2,17.1,193.0,3400.0,Female
45,Adelie,Dream,39.6,18.8,190.0,4600.0,Male
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
141,Adelie,Dream,40.6,17.2,187.0,3475.0,Male
90,Adelie,Dream,35.7,18.0,202.0,3550.0,Female
49,Adelie,Dream,42.3,21.2,191.0,4150.0,Male
86,Adelie,Dream,36.3,19.5,190.0,3800.0,Male
146,Adelie,Dream,39.2,18.6,190.0,4250.0,Male

In [3]:
# 2. String expressions — matches pytae CLI -qry syntax; supports comma-separated conditions
(
    penguins
    .pt.qry("species = 'Adelie', body_mass_g > 4000")
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
67,Adelie,Biscoe,41.1,19.1,188.0,4100.0,Male
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,Male
133,Adelie,Dream,37.5,18.5,199.0,4475.0,Male
39,Adelie,Dream,39.8,19.1,184.0,4650.0,Male
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,Male
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,Male
111,Adelie,Biscoe,45.6,20.3,191.0,4600.0,Male
103,Adelie,Biscoe,37.8,20.0,190.0,4250.0,Male
115,Adelie,Biscoe,42.7,18.3,196.0,4075.0,Male

In [4]:
# 3. Plain dictionaries — useful for programmatic pipelines or dynamic key mapping
(
    penguins
    .pt.qry({"species": "Adelie", "island": "Dream"})
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
87,Adelie,Dream,36.9,18.6,189.0,3500.0,Female
136,Adelie,Dream,35.6,17.5,191.0,3175.0,Female
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female
32,Adelie,Dream,39.5,17.8,188.0,3300.0,Female
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male
89,Adelie,Dream,38.9,18.8,190.0,3600.0,Female
85,Adelie,Dream,41.3,20.3,194.0,3550.0,Male
142,Adelie,Dream,32.1,15.5,188.0,3050.0,Female
86,Adelie,Dream,36.3,19.5,190.0,3800.0,Male
139,Adelie,Dream,39.7,17.9,193.0,4250.0,Male

In [5]:
# 4. Mixed calling — combine string expressions, dicts, and kwargs in a single call
(
    penguins
    .pt.qry("body_mass_g > 4000", {"island": "Biscoe"}, sex="Female")
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
270,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,Female
317,Gentoo,Biscoe,46.9,14.6,222.0,4875.0,Female
298,Gentoo,Biscoe,45.2,13.8,215.0,4750.0,Female
276,Gentoo,Biscoe,43.8,13.9,208.0,4300.0,Female
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
288,Gentoo,Biscoe,43.5,14.2,220.0,4700.0,Female
262,Gentoo,Biscoe,45.3,13.7,210.0,4300.0,Female
232,Gentoo,Biscoe,45.5,13.7,214.0,4650.0,Female
310,Gentoo,Biscoe,47.5,15.0,218.0,4950.0,Female
238,Gentoo,Biscoe,46.2,14.5,209.0,4800.0,Female

In [6]:
# 5. Top-level function pt.qry(df, ...) — works identically to the .pt accessor
pt.qry(penguins, species="Gentoo", body_mass_g="> 5000").sample(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,Male
279,Gentoo,Biscoe,50.4,15.3,224.0,5550.0,Male
247,Gentoo,Biscoe,47.8,15.0,215.0,5650.0,Male
268,Gentoo,Biscoe,44.9,13.3,213.0,5100.0,Female
307,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,Male
313,Gentoo,Biscoe,49.5,16.1,224.0,5650.0,Male
327,Gentoo,Biscoe,53.4,15.8,219.0,5500.0,Male
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,Male
269,Gentoo,Biscoe,45.2,15.8,215.0,5300.0,Male
239,Gentoo,Biscoe,48.7,15.1,222.0,5350.0,Male

## Column names with spaces — bracket notation `[col]`

When columns have spaces (like `'bill length mm'`), enclose them in square brackets `[col]` inside string expressions. This avoids keyword argument restrictions and dictionary unpacking entirely.

In [7]:
# DataFrame with spaces in column names
penguins_spaces = penguins.rename(
    columns={'bill_length_mm': 'bill length mm', 'body_mass_g': 'body mass g'}
)

# String expressions with brackets handle spaced column names cleanly:
(
    penguins_spaces
    .pt.qry("[bill length mm] > 45", "[body mass g] > 4000")
    .sample(10)
)

,species,island,bill length mm,bill_depth_mm,flipper_length_mm,body mass g,sex
238,Gentoo,Biscoe,46.2,14.5,209.0,4800.0,Female
242,Gentoo,Biscoe,46.5,14.5,213.0,4400.0,Female
307,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,Male
292,Gentoo,Biscoe,48.2,15.6,221.0,5100.0,Male
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,Male
322,Gentoo,Biscoe,47.2,15.5,215.0,4975.0,Female
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,Male
181,Chinstrap,Dream,52.8,20.0,205.0,4550.0,Male
286,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN
277,Gentoo,Biscoe,45.5,15.0,220.0,5000.0,Male

In [8]:
# DataFrame with spaces in column names
penguins_spaces = penguins.rename(
    columns={'bill_length_mm': 'bill length mm', 'body_mass_g': 'body mass g'}
)

# String expressions with brackets handle spaced column names cleanly:
(
    penguins_spaces
    .pt.qry("[bill length mm] > 45", "[body mass g] > 4000")
    .sample(10)
)

,species,island,bill length mm,bill_depth_mm,flipper_length_mm,body mass g,sex
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,Male
255,Gentoo,Biscoe,48.4,16.3,220.0,5400.0,Male
316,Gentoo,Biscoe,49.4,15.8,216.0,4925.0,Male
237,Gentoo,Biscoe,49.2,15.2,221.0,6300.0,Male
267,Gentoo,Biscoe,50.5,15.9,225.0,5400.0,Male
262,Gentoo,Biscoe,45.3,13.7,210.0,4300.0,Female
271,Gentoo,Biscoe,48.5,14.1,220.0,5300.0,Male
293,Gentoo,Biscoe,46.5,14.8,217.0,5200.0,Female
225,Gentoo,Biscoe,46.5,13.5,210.0,4550.0,Female
333,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,Male

## Equality and multi-value filters

In [9]:
# Single equality — keep only Dream island
(
    penguins
    .pt.qry(island='Dream')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
151,Adelie,Dream,41.5,18.5,201.0,4000.0,Male
150,Adelie,Dream,36.0,17.1,187.0,3700.0,Female
158,Chinstrap,Dream,46.1,18.2,178.0,3250.0,Female
219,Chinstrap,Dream,50.2,18.7,198.0,3775.0,Female
148,Adelie,Dream,36.0,17.8,195.0,3450.0,Female
89,Adelie,Dream,38.9,18.8,190.0,3600.0,Female
168,Chinstrap,Dream,50.3,20.0,197.0,3300.0,Male
212,Chinstrap,Dream,51.9,19.5,206.0,3950.0,Male
141,Adelie,Dream,40.6,17.2,187.0,3475.0,Male
188,Chinstrap,Dream,47.6,18.3,195.0,3850.0,Female

In [10]:
# List — keep Adelie and Chinstrap, aggregate per species + island
# Kwargs accept a list directly:
(
    penguins
    .pt.qry(species=['Adelie', 'Chinstrap'])
    .pt.select('species', 'island', 'body_mass_g')
    .pt.agg_df(['species', 'island'], a=['mean', 'n'])
)

     species     island   n  body_mass_g
0     Adelie     Biscoe  44  3709.659091
1     Adelie      Dream  56  3688.392857
2     Adelie  Torgersen  52  3706.372549
3  Chinstrap      Dream  68  3733.088235

In [11]:
# 'not in' — exclude Male penguins via kwargs
(
    penguins
    .pt.qry(sex=('not in', ['Male']))
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
252,Gentoo,Biscoe,45.1,14.5,207.0,5050.0,Female
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,Female
56,Adelie,Biscoe,39.0,17.5,186.0,3550.0,Female
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,Female
202,Chinstrap,Dream,48.1,16.4,199.0,3325.0,Female
25,Adelie,Biscoe,35.3,18.9,187.0,3800.0,Female
74,Adelie,Torgersen,35.5,17.5,190.0,3700.0,Female
34,Adelie,Dream,36.4,17.0,195.0,3325.0,Female
166,Chinstrap,Dream,45.9,17.1,190.0,3575.0,Female
140,Adelie,Dream,40.2,17.1,193.0,3400.0,Female

## Comparison operators

Comparison filters can be written as string expressions (`body_mass_g="> 5000"`) or operator tuples (`body_mass_g=('>', 5000)`).
Supported comparison operators: `>`, `>=`, `<`, `<=`, `==`, `!=`.

In [12]:
# Filter penguins with body mass greater than 5000g (string operator)
(
    penguins
    .pt.qry(body_mass_g='> 5000')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,Male
283,Gentoo,Biscoe,54.3,15.7,231.0,5650.0,Male
289,Gentoo,Biscoe,50.7,15.0,223.0,5550.0,Male
307,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,Male
301,Gentoo,Biscoe,52.5,15.6,221.0,5450.0,Male
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,Male
287,Gentoo,Biscoe,49.5,16.2,229.0,5800.0,Male
239,Gentoo,Biscoe,48.7,15.1,222.0,5350.0,Male
305,Gentoo,Biscoe,50.8,17.3,228.0,5600.0,Male
261,Gentoo,Biscoe,49.6,16.0,225.0,5700.0,Male

In [13]:
# Tuple operator syntax: ('>', 5000)
(
    penguins
    .pt.qry(body_mass_g=('>', 5000))
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
283,Gentoo,Biscoe,54.3,15.7,231.0,5650.0,Male
333,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,Male
287,Gentoo,Biscoe,49.5,16.2,229.0,5800.0,Male
295,Gentoo,Biscoe,48.6,16.0,230.0,5800.0,Male
245,Gentoo,Biscoe,46.1,15.1,215.0,5100.0,Male
259,Gentoo,Biscoe,48.7,15.7,208.0,5350.0,Male
249,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,Male
297,Gentoo,Biscoe,51.1,16.3,220.0,6000.0,Male
279,Gentoo,Biscoe,50.4,15.3,224.0,5550.0,Male
307,Gentoo,Biscoe,51.3,14.2,218.0,5300.0,Male

In [14]:
# Combine multiple column conditions in one qry call
# Gentoo females with large bills — multi-condition kwargs:
(
    penguins
    .pt.qry(species='Gentoo', sex='Female', bill_length_mm='>= 45')
    .pt.select('species', 'island', 'sex', 'bill_length_mm', 'body_mass_g')
    .sample(10)
)

    species  island     sex  bill_length_mm  body_mass_g
262  Gentoo  Biscoe  Female            45.3       4300.0
340  Gentoo  Biscoe  Female            46.8       4850.0
322  Gentoo  Biscoe  Female            47.2       4975.0
222  Gentoo  Biscoe  Female            48.7       4450.0
317  Gentoo  Biscoe  Female            46.9       4875.0
293  Gentoo  Biscoe  Female            46.5       5200.0
318  Gentoo  Biscoe  Female            48.4       4625.0
302  Gentoo  Biscoe  Female            47.4       4725.0
238  Gentoo  Biscoe  Female            46.2       4800.0
284  Gentoo  Biscoe  Female            45.8       4700.0

## Interval notation
String intervals let you filter a range on the same column without chaining two `.pt.qry()` calls.
`(` / `)` = exclusive bound, `[` / `]` = inclusive bound.

In [15]:
# Open interval — strictly between 3500 and 4500 g via kwargs:
(
    penguins
    .pt.qry(body_mass_g='(3500,4500)')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
163,Chinstrap,Dream,51.7,20.3,194.0,3775.0,Male
135,Adelie,Dream,41.1,17.5,190.0,3900.0,Male
78,Adelie,Torgersen,36.2,16.1,187.0,3550.0,Female
179,Chinstrap,Dream,49.5,19.0,200.0,3800.0,Male
219,Chinstrap,Dream,50.2,18.7,198.0,3775.0,Female
187,Chinstrap,Dream,47.5,16.8,199.0,3900.0,Female
76,Adelie,Torgersen,40.9,16.8,191.0,3700.0,Female
25,Adelie,Biscoe,35.3,18.9,187.0,3800.0,Female
211,Chinstrap,Dream,45.6,19.4,194.0,3525.0,Female
218,Chinstrap,Dream,50.8,19.0,210.0,4100.0,Male

In [16]:
# Half-open interval — bill_length_mm >= 40 and < 50
(
    penguins
    .pt.qry(bill_length_mm='[40,50)')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
259,Gentoo,Biscoe,48.7,15.7,208.0,5350.0,Male
285,Gentoo,Biscoe,49.8,16.8,230.0,5700.0,Male
204,Chinstrap,Dream,45.7,17.3,193.0,3600.0,Female
260,Gentoo,Biscoe,42.7,13.7,208.0,3950.0,Female
216,Chinstrap,Dream,43.5,18.1,202.0,3400.0,Female
186,Chinstrap,Dream,49.7,18.6,195.0,3600.0,Male
293,Gentoo,Biscoe,46.5,14.8,217.0,5200.0,Female
316,Gentoo,Biscoe,49.4,15.8,216.0,4925.0,Male
306,Gentoo,Biscoe,43.4,14.4,218.0,4600.0,Female
317,Gentoo,Biscoe,46.9,14.6,222.0,4875.0,Female

In [17]:
# Closed interval — body_mass_g between 3500 and 4000 inclusive
(
    penguins
    .pt.qry(body_mass_g='[3500,4000]')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
152,Chinstrap,Dream,46.5,17.9,192.0,3500.0,Female
74,Adelie,Torgersen,35.5,17.5,190.0,3700.0,Female
164,Chinstrap,Dream,47.0,17.3,185.0,3700.0,Female
79,Adelie,Torgersen,42.1,19.1,195.0,4000.0,Male
162,Chinstrap,Dream,46.6,17.8,193.0,3800.0,Female
188,Chinstrap,Dream,47.6,18.3,195.0,3850.0,Female
78,Adelie,Torgersen,36.2,16.1,187.0,3550.0,Female
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,Male
204,Chinstrap,Dream,45.7,17.3,193.0,3600.0,Female
175,Chinstrap,Dream,50.6,19.4,193.0,3800.0,Male

In [18]:
# Interval notation also works on STRING columns — alphabetical comparison
# 'island' values: Biscoe, Dream, Torgersen — (Biscoe, Dream] means Dream only
(
    penguins
    .pt.qry(island='(Biscoe,Dream]')
    .sample()
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
171,Chinstrap,Dream,49.2,18.2,195.0,4400.0,Male

## String matching and null checks
`startswith`/`endswith`/`contains`/`regex` use pandas' `.str` accessor (missing values never match, `na=False`). `contains`/`regex` both search anywhere in the string (like `re.search`) — `regex` is just `contains` with `regex=True`.

`startswith` and `endswith` also accept a list or tuple of multiple prefixes/suffixes. `isna`/`notna` are one-element tuples since they take no value.

In [19]:
# species starting with 'Ad' — same idea for endswith/contains
(
    penguins
    .pt.qry(species=('startswith', 'Ad'))
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
124,Adelie,Torgersen,35.2,15.9,186.0,3050.0,Female
79,Adelie,Torgersen,42.1,19.1,195.0,4000.0,Male
62,Adelie,Biscoe,37.6,17.0,185.0,3600.0,Female
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,Male
122,Adelie,Torgersen,40.2,17.0,176.0,3450.0,Female
95,Adelie,Dream,40.8,18.9,208.0,4300.0,Male
90,Adelie,Dream,35.7,18.0,202.0,3550.0,Female
114,Adelie,Biscoe,39.6,20.7,191.0,3900.0,Female
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,Female
74,Adelie,Torgersen,35.5,17.5,190.0,3700.0,Female

In [20]:
# Multiple prefixes: species starting with 'Ad' OR 'Ge'
(
    penguins
    .pt.qry(species=('startswith', ['Ad', 'Ge']))
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
270,Gentoo,Biscoe,46.6,14.2,210.0,4850.0,Female
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
141,Adelie,Dream,40.6,17.2,187.0,3475.0,Male
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,Female
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
315,Gentoo,Biscoe,50.8,15.7,226.0,5200.0,Male
325,Gentoo,Biscoe,46.8,16.1,215.0,5500.0,Male
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
323,Gentoo,Biscoe,49.1,15.0,228.0,5500.0,Male
76,Adelie,Torgersen,40.9,16.8,191.0,3700.0,Female

In [21]:
# regex, search-anywhere (like re.search) — species containing a repeated 'o'
(
    penguins
    .pt.qry(species=('regex', r'oo'))
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
233,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,Male
259,Gentoo,Biscoe,48.7,15.7,208.0,5350.0,Male
274,Gentoo,Biscoe,46.5,14.4,217.0,4900.0,Female
280,Gentoo,Biscoe,45.3,13.8,208.0,4200.0,Female
316,Gentoo,Biscoe,49.4,15.8,216.0,4925.0,Male
312,Gentoo,Biscoe,45.5,14.5,212.0,4750.0,Female
300,Gentoo,Biscoe,49.1,14.5,212.0,4625.0,Female
250,Gentoo,Biscoe,47.3,15.3,222.0,5250.0,Male
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,Female
246,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN

In [22]:
# isna/notna — rows with a missing 'sex' value (one-element tuple, no value needed)
(
    penguins
    .pt.qry(sex=('isna',))
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN
246,Gentoo,Biscoe,44.5,14.3,216.0,4100.0,NaN
286,Gentoo,Biscoe,46.2,14.4,214.0,4650.0,NaN
324,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN
336,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN

## Multiple conditions on the same column

Because Python keyword arguments must have unique names, you cannot pass `bill_length_mm='> 40', bill_length_mm='< 50'` in kwargs. With `qry()`, you have multiple intuitive solutions:

1. **Comma-separated string expression**: `"bill_length_mm > 40, bill_length_mm < 50"`
2. **Multiple positional string arguments**: `"bill_length_mm > 40", "bill_length_mm < 50"`
3. **Interval notation**: `bill_length_mm='[40,50)'`
4. **Chained `.pt.qry()` calls**: `.pt.qry(bill_length_mm='> 40').pt.qry(bill_length_mm='< 50')`

In [23]:
# Comma-separated string expression on the same column:
(
    penguins
    .pt.qry("bill_length_mm > 40, bill_length_mm < 50")
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
324,Gentoo,Biscoe,47.3,13.8,216.0,4725.0,NaN
235,Gentoo,Biscoe,49.3,15.7,217.0,5850.0,Male
292,Gentoo,Biscoe,48.2,15.6,221.0,5100.0,Male
217,Chinstrap,Dream,49.6,18.2,193.0,3775.0,Male
255,Gentoo,Biscoe,48.4,16.3,220.0,5400.0,Male
180,Chinstrap,Dream,46.4,17.8,191.0,3700.0,Female
152,Chinstrap,Dream,46.5,17.9,192.0,3500.0,Female
323,Gentoo,Biscoe,49.1,15.0,228.0,5500.0,Male
336,Gentoo,Biscoe,44.5,15.7,217.0,4875.0,NaN
143,Adelie,Dream,40.7,17.0,190.0,3725.0,Male

In [24]:
# Multiple string arguments:
(
    penguins
    .pt.qry("bill_length_mm > 40", "bill_length_mm < 50")
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
76,Adelie,Torgersen,40.9,16.8,191.0,3700.0,Female
180,Chinstrap,Dream,46.4,17.8,191.0,3700.0,Female
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,Male
308,Gentoo,Biscoe,47.5,14.0,212.0,4875.0,Female
201,Chinstrap,Dream,49.8,17.3,198.0,3675.0,Female
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
332,Gentoo,Biscoe,43.5,15.2,213.0,4650.0,Female
244,Gentoo,Biscoe,42.9,13.1,215.0,5000.0,Female
251,Gentoo,Biscoe,42.8,14.2,209.0,4700.0,Female
123,Adelie,Torgersen,41.4,18.5,202.0,3875.0,Male

In [25]:
# Chaining two .pt.qry() calls:
(
    penguins
    .pt.qry(bill_length_mm='> 40')
    .pt.qry(bill_length_mm='< 50')
    .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,Female
233,Gentoo,Biscoe,48.4,14.6,213.0,5850.0,Male
220,Gentoo,Biscoe,46.1,13.2,211.0,4500.0,Female
294,Gentoo,Biscoe,46.4,15.0,216.0,4700.0,Female
129,Adelie,Torgersen,44.1,18.0,210.0,4000.0,Male
322,Gentoo,Biscoe,47.2,15.5,215.0,4975.0,Female
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,Male
33,Adelie,Dream,40.9,18.9,184.0,3900.0,Male
268,Gentoo,Biscoe,44.9,13.3,213.0,5100.0,Female
63,Adelie,Biscoe,41.1,18.2,192.0,4050.0,Male

## Helpful typo suggestions

If a column name is misspelled, `qry()` suggests close matches using fuzzy matching to help catch typos immediately.

In [26]:
# Intentional typo 'speceis' raises KeyError with a helpful suggestion
try:
    penguins.pt.qry(speceis='Adelie')
except KeyError as exc:
    print("Caught expected error:", exc)

Caught expected error: "unknown column 'speceis' (did you mean 'species'?)"

## Real-world pipeline: filter → select → aggregate

In [27]:
# Tips: weekend dinner table of 2+, spending > $10 — average tip and bill by smoker status
# Using bracket notation [total bill] across qry, select, and agg_df:
(
    tips
    .rename(columns={'total_bill': 'total bill'})
    .pt.qry("[total bill] > 10", day=['Sat', 'Sun'], time='Dinner', size='>= 2')
    .pt.select('smoker', 'tip', '[total bill]')
    .pt.agg_df('smoker', "tip = mean, [total bill] = mean, n = n")
)

  smoker       tip  total bill   n
0    Yes  3.087719   23.232281  57
1     No  3.225464   20.705876  97