# `agg_df` — Reference

`agg_df` aggregates numeric columns, automatically grouping by all non-numeric columns.

### Calling Styles

1. **Keyword arguments** (recommended): `.pt.agg_df(cnt='n', bill_length_mm='mean', body_mass_g=['sum', 'mean'])`
2. **Simple aggregate string or list**: `.pt.agg_df("mean")` or `.pt.agg_df(["sum", "mean", "n"])

---

In [1]:
import sys, os
_src = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if _src not in sys.path: sys.path.insert(0, _src)

import pytae as pt

penguins = pt.sample_data['penguins']
tips = pt.sample_data['tips']
titanic = pt.sample_data['titanic']

## List `a` — `n` always goes first

In [2]:
# mean + n: regardless of list order, n always comes first before aggregated columns
(penguins
 .pt.select('species', 'island', 'bill_length_mm', 'body_mass_g')
 .pt.agg_df(a=['mean', 'n'])  # notice n comes first
)

     species     island    n  bill_length_mm  body_mass_g
0     Adelie     Biscoe   44       38.975000  3709.659091
1     Adelie      Dream   56       38.501786  3688.392857
2     Adelie  Torgersen   52       38.950980  3706.372549
3  Chinstrap      Dream   68       48.833824  3733.088235
4     Gentoo     Biscoe  124       47.504878  5076.016260

In [3]:
# Multiple numeric aggregations — column names get suffix: col_sum, col_mean, col_max
# also works with a single string if you only need one aggfunc
(penguins
 .pt.select('species', 'bill_length_mm', 'body_mass_g')
 .pt.agg_df(a=['sum', 'mean', 'max', 'n'])
)

,species,n,bill_length_mm_sum,bill_length_mm_mean,bill_length_mm_max,body_mass_g_sum,body_mass_g_mean,body_mass_g_max
0,Adelie,152,5857.5,38.791391,46.0,558800.0,3700.662252,4775.0
1,Chinstrap,68,3320.7,48.833824,58.0,253850.0,3733.088235,4800.0
2,Gentoo,124,5843.1,47.504878,59.6,624350.0,5076.016260,6300.0

## Keyword arguments — per-column control, output order follows parameter order

In [4]:
# Keyword arguments — mean for bill_length, sum+mean for body_mass, count named 'n'
(penguins
 .pt.agg_df(
     bill_length_mm='mean',
     body_mass_g=['sum', 'mean'],
     n='n',
 )
)

,species,island,sex,bill_length_mm,body_mass_g_sum,body_mass_g_mean,n
0,Adelie,Biscoe,Female,37.359091,74125.0,3369.318182,22
1,Adelie,Biscoe,Male,40.590909,89100.0,4050.000000,22
2,Adelie,Dream,Female,36.911111,90300.0,3344.444444,27
3,Adelie,Dream,Male,40.071429,113275.0,4045.535714,28
4,Adelie,Torgersen,Female,37.554167,81500.0,3395.833333,24
5,Adelie,Torgersen,Male,40.586957,92800.0,4034.782609,23
6,Chinstrap,Dream,Female,46.573529,119925.0,3527.205882,34
7,Chinstrap,Dream,Male,51.094118,133925.0,3938.970588,34
8,Gentoo,Biscoe,Female,45.563793,271425.0,4679.741379,58
9,Gentoo,Biscoe,Male,49.473770,334575.0,5484.836066,61

In [5]:
# Place count first (n at front), then aggregations
# Output order follows parameter order
# Note: the count keyword can be named anything — 'cnt', 'count', even 'maddy'
(
    tips
    .pt.select('smoker', 'time', 'total_bill', 'tip')
    .pt.agg_df(cnt='n', total_bill='mean', tip=['mean', 'max'])
)

  smoker    time  cnt  total_bill  tip_mean  tip_max
0    Yes   Lunch   23   17.399130  2.834348      5.0
1    Yes  Dinner   70   21.859429  3.066000     10.0
2     No   Lunch   45   17.050889  2.673778      6.7
3     No  Dinner  106   20.095660  3.126887      9.0

In [6]:
# You can name the count column anything you like as a keyword argument
# Here maddy='n' creates a column called 'maddy' that holds the group count
(
    penguins
    .pt.select('species', 'island', 'body_mass_g')
    .pt.agg_df(maddy='n', body_mass_g='sum')
)

     species     island  maddy  body_mass_g
0     Adelie     Biscoe     44     163225.0
1     Adelie      Dream     56     206550.0
2     Adelie  Torgersen     52     189025.0
3  Chinstrap      Dream     68     253850.0
4     Gentoo     Biscoe    124     624350.0

In [7]:
# Multiple count columns as keyword arguments — each count gets its own name
(
    penguins
    .pt.select('species', 'island', 'body_mass_g')
    .pt.agg_df(count='n', countv2='n', body_mass_g='mean')
)

     species     island  count  countv2  body_mass_g
0     Adelie     Biscoe     44       44  3709.659091
1     Adelie      Dream     56       56  3688.392857
2     Adelie  Torgersen     52       52  3706.372549
3  Chinstrap      Dream     68       68  3733.088235
4     Gentoo     Biscoe    124      124  5076.016260

In [8]:
# median is a standard aggfunc — works in list form or as keyword argument
(
    penguins
    .pt.select('species', 'island', 'bill_length_mm', 'body_mass_g')
    .pt.agg_df(a=['median', 'mean', 'n'])
)

,species,island,n,bill_length_mm_median,bill_length_mm_mean,body_mass_g_median,body_mass_g_mean
0,Adelie,Biscoe,44,38.70,38.975000,3750.0,3709.659091
1,Adelie,Dream,56,38.55,38.501786,3575.0,3688.392857
2,Adelie,Torgersen,52,38.90,38.950980,3700.0,3706.372549
3,Chinstrap,Dream,68,49.55,48.833824,3700.0,3733.088235
4,Gentoo,Biscoe,124,47.30,47.504878,5000.0,5076.016260

## `dropna=False` — include groups with NaN keys

In [9]:
# Penguins has NaN in 'sex' — dropna=False keeps those rows in their own group
(penguins
 .pt.select('species', 'sex', 'bill_length_mm', 'body_mass_g')
 .pt.agg_df(a=['mean', 'n'], dropna=False)
)

     species     sex   n  bill_length_mm  body_mass_g
0     Adelie  Female  73       37.257534  3368.835616
1     Adelie    Male  73       40.390411  4043.493151
2     Adelie     NaN   6       37.840000  3540.000000
3  Chinstrap  Female  34       46.573529  3527.205882
4  Chinstrap    Male  34       51.094118  3938.970588
5     Gentoo  Female  58       45.563793  4679.741379
6     Gentoo    Male  61       49.473770  5484.836066
7     Gentoo     NaN   5       45.625000  4587.500000

In [10]:
# with default dropna=True
(penguins
 .pt.select('species', 'sex', 'bill_length_mm', 'body_mass_g')
 .pt.agg_df(a=['mean', 'n'])
)

     species     sex   n  bill_length_mm  body_mass_g
0     Adelie  Female  73       37.257534  3368.835616
1     Adelie    Male  73       40.390411  4043.493151
2  Chinstrap  Female  34       46.573529  3527.205882
3  Chinstrap    Male  34       51.094118  3938.970588
4     Gentoo  Female  58       45.563793  4679.741379
5     Gentoo    Male  61       49.473770  5484.836066

## `n`-only aggregation — count with no numeric columns needed

In [11]:
# Count only — useful for frequency tables on categorical columns
(penguins
 .pt.select(exclude_dtype='number')
 .pt.agg_df(a='n')
)

     species     island     sex   n
0     Adelie     Biscoe  Female  22
1     Adelie     Biscoe    Male  22
2     Adelie      Dream  Female  27
3     Adelie      Dream    Male  28
4     Adelie  Torgersen  Female  24
5     Adelie  Torgersen    Male  23
6  Chinstrap      Dream  Female  34
7  Chinstrap      Dream    Male  34
8     Gentoo     Biscoe  Female  58
9     Gentoo     Biscoe    Male  61