# Other Utilities — Reference

| Utility | Purpose |
|---|---|
| `.cols()` | List column names sorted or in original order |
| `.handle_missing()` | Fill string NaN with a marker, numeric NaN with 0, strip whitespace |
| `.group_x()` | Add a group-level scalar back to every row (via `transform`) |
| `.clean_columns()` | Clean column header names (strip, squeeze, fill, case, dedupe) |
| `.replace_values()` | Replace values, optionally scoped to columns, exact or substring match |
| `.to_clip()` | Copy DataFrame to clipboard (tab-separated, no index) |

---

In [1]:
import sys, os
_src = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if _src not in sys.path: sys.path.insert(0, _src)

import pytae as pt

penguins = pt.sample_data['penguins']
titanic = pt.sample_data['titanic']

In [2]:
# Alphabetical column list — useful for quick discovery
penguins.cols()

['bill_depth_mm',
 'bill_length_mm',
 'body_mass_g',
 'flipper_length_mm',
 'island',
 'sex',
 'species']

In [3]:
# Descending alphabetical sort — useful when column names form a natural reverse order
penguins.cols(ascending=False)

['species',
 'sex',
 'island',
 'flipper_length_mm',
 'body_mass_g',
 'bill_length_mm',
 'bill_depth_mm']

## `handle_missing()` — clean before aggregating
Fills string/category NaN with a visible marker (default `.`) and numeric NaN with `0`. Also strips leading/trailing whitespace from string columns.

In [4]:
# Default fillna='.': NaN sex becomes '.', NaN numerics become 0
# Then aggregate to see the '.' group alongside real groups
(penguins
 .handle_missing()
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,0.0,0.0,0.0,0.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,0.0,0.0,0.0,0.0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [5]:
# Custom fillna marker — makes missing group explicit in reports
( penguins
 .handle_missing(fillna='Unknown')
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,0.0,0.0,0.0,0.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,0.0,0.0,0.0,0.0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [6]:
# Use a single-char marker like '$' to make missing data stand out in reports
( penguins
 .handle_missing(fillna='$')
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,0.0,0.0,0.0,0.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,0.0,0.0,0.0,0.0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## `group_x()` — broadcast a group aggregate back to every row
Unlike `agg_df` which collapses rows, `group_x` **adds a column** to the original DataFrame using `transform`. Useful for computing a group value alongside row-level detail (e.g., share of group total, deviation from group mean).

In [7]:
# Default: count per group (a='n') — adds column 'n' to every row
( penguins
 .handle_missing()
 .group_x(group=['species','island' ])
 .select(['species', 'island', 'sex', 'body_mass_g', 'n'])
 .sample(10)
)

       species     island     sex  body_mass_g    n
165  Chinstrap      Dream    Male       4050.0   68
24      Adelie     Biscoe    Male       3800.0   44
111     Adelie     Biscoe    Male       4600.0   44
320     Gentoo     Biscoe  Female       4850.0  124
241     Gentoo     Biscoe  Female       5000.0  124
164  Chinstrap      Dream  Female       3700.0   68
4       Adelie  Torgersen  Female       3450.0   52
261     Gentoo     Biscoe    Male       5700.0  124
91      Adelie      Dream    Male       4300.0   56
139     Adelie      Dream    Male       4250.0   56

In [8]:
# instead of count, group_x with value + aggfunc: add group mean of body_mass_g to every row
(penguins
 .group_x(group=['species'], v='body_mass_g', a='mean')
 .rename(columns={'x': 'species_mean_mass'})
 .sample(10)
)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_mean_mass
306,Gentoo,Biscoe,43.4,14.4,218.0,4600.0,Female,5076.016260
112,Adelie,Biscoe,39.7,17.7,193.0,3200.0,Female,3700.662252
261,Gentoo,Biscoe,49.6,16.0,225.0,5700.0,Male,5076.016260
134,Adelie,Dream,38.1,17.6,187.0,3425.0,Female,3700.662252
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,Male,3700.662252
135,Adelie,Dream,41.1,17.5,190.0,3900.0,Male,3700.662252
156,Chinstrap,Dream,52.7,19.8,197.0,3725.0,Male,3733.088235
249,Gentoo,Biscoe,50.0,15.3,220.0,5550.0,Male,5076.016260
333,Gentoo,Biscoe,51.5,16.3,230.0,5500.0,Male,5076.016260
254,Gentoo,Biscoe,49.1,14.8,220.0,5150.0,Female,5076.016260

In [9]:
#with dropna=False
penguins.group_x(group=['species', 'sex'],dropna=False)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,n
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,73
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,73
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,73
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,6
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,73
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,5
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,58
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,61
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,58
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,61

In [10]:
#with default dropna=True
penguins.group_x(group=['species', 'sex'])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,n
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,73.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,73.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,73.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,73.0
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,58.0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,61.0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,58.0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,61.0

## `to_clip()` — copy to clipboard
`to_clip()` copies the DataFrame to the system clipboard as tab-separated text (no index). Paste directly into Excel, Google Sheets, or any text editor. Invisible in notebook output — run it and then paste.

In [11]:
# to_clip() copies the current DataFrame to clipboard — paste into Excel/Sheets
# Run this cell then Cmd+V in any spreadsheet application
(penguins
 .select(['species', 'island', 'bill_length_mm', 'body_mass_g'])
 .agg_df(a=['mean', 'n'])
 .to_clip()
)

## `clean_columns()` — clean messy header names
Cleans column header names in a fixed order: `strip` -> `strip_special` -> `squeeze` -> `fill` -> `case` -> `dedupe`. Handy after loading a spreadsheet export with inconsistent spacing/casing.

In [ ]:
# messy headers: leading/trailing spaces, repeated internal spaces, mixed case
messy = penguins.rename(columns={
    "species": "  Species  ",
    "island": "Island   Name",
    "body_mass_g": "Body Mass (g)",
})

(messy
 .clean_columns(strip=True, squeeze=True, strip_special=True, fill="_", case="lower")
 .cols(ascending=None)
)

In [ ]:
# Proper/Title Case, no fill — spaces in header names are left alone
penguins.clean_columns(case="proper").cols(ascending=None)

## `replace_values()` — replace values, whole-cell or substring
Wraps pandas `replace()`. `exact=True` (default) only replaces a cell whose entire value matches a key exactly; `exact=False` replaces a key anywhere it occurs as a substring, leaving the rest of the cell untouched. Optionally scope to specific columns with `c=`. Parameter names (`v=`, `c=`, `exact=`) match the `-replace_values` CLI flag.

In [ ]:
# exact=True (default): only cells that equal 'Adelie'/'Male' exactly are replaced
(penguins
 .replace_values({"Adelie": "Adelie (renamed)", "Male": "M"})
 .select(["species", "sex"])
 .drop_duplicates()
)

In [ ]:
# c= restricts the replace to specific columns — 'island' untouched even though
# it never contained 'Male' anyway, this shows the scoping mechanism itself
(penguins
 .replace_values({"Male": "M", "Female": "F"}, c="sex")
 .select(["island", "sex"])
 .drop_duplicates()
)

In [ ]:
# exact=False: substring match anywhere in the cell, rest of the cell untouched
import pandas as pd

notes = pd.DataFrame({"note": ["a magician performed", "not a magician exactly", "no match here"]})
notes.replace_values({"a magician": "the magic"}, exact=False)