# Other Utilities — Reference

| Utility | Purpose |
|---|---|
| `pt.cols()` | List column names sorted or in original order |
| `pt.handle_missing()` | Fill string NaN with a marker, numeric NaN with 0, strip whitespace |
| `pt.group_x()` | Add a group-level scalar back to every row (via `transform`) |
| `pt.clean_columns()` | Clean column header names (strip, squeeze, fill, case, dedupe) |
| `pt.replace_values()` | Replace values, optionally scoped to columns, exact or substring match |
| `pt.to_clip()` | Copy DataFrame to clipboard (tab-separated, no index) |

---

In [1]:
import sys, os
_src = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if _src not in sys.path: sys.path.insert(0, _src)

import pytae as pt

penguins = pt.sample_data['penguins']
titanic = pt.sample_data['titanic']

In [2]:
# Alphabetical column list — useful for quick discovery
pt.cols(penguins)

['bill_depth_mm',
 'bill_length_mm',
 'body_mass_g',
 'flipper_length_mm',
 'island',
 'sex',
 'species']

In [3]:
# Descending alphabetical sort — useful when column names form a natural reverse order
pt.cols(penguins, ascending=False)

['species',
 'sex',
 'island',
 'flipper_length_mm',
 'body_mass_g',
 'bill_length_mm',
 'bill_depth_mm']

## `handle_missing()` — clean before aggregating
Fills string/category NaN with a visible marker (default `.`) and numeric NaN with `0`. Also strips leading/trailing whitespace from string columns.

In [4]:
# Default fillna='.': NaN sex becomes '.', NaN numerics become 0
# Then aggregate to see the '.' group alongside real groups
pt.handle_missing(penguins)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,0.0,0.0,0.0,0.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,0.0,0.0,0.0,0.0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [5]:
# Custom fillna marker — makes missing group explicit in reports
pt.handle_missing(penguins, fillna='Unknown')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,0.0,0.0,0.0,0.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,0.0,0.0,0.0,0.0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

In [6]:
# Use a single-char marker like '$' to make missing data stand out in reports
pt.handle_missing(penguins, fillna='$')

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,0.0,0.0,0.0,0.0,0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,0.0,0.0,0.0,0.0,0
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

## `group_x()` — broadcast a group aggregate back to every row
Unlike `agg_df` which collapses rows, `group_x` **adds a column** to the original DataFrame using `transform`. Useful for computing a group value alongside row-level detail (e.g., share of group total, deviation from group mean).

In [7]:
# Default: count per group (a='n') — adds column 'n' to every row
(pt.select(pt.group_x(pt.handle_missing(penguins), group=['species','island' ]), 'species', 'island', 'sex', 'body_mass_g', 'n').sample(10))

       species     island     sex  body_mass_g    n
250     Gentoo     Biscoe    Male       5250.0  124
38      Adelie      Dream  Female       3300.0   56
123     Adelie  Torgersen    Male       3875.0   52
178  Chinstrap      Dream  Female       3400.0   68
242     Gentoo     Biscoe  Female       4400.0  124
110     Adelie     Biscoe  Female       3825.0   44
107     Adelie     Biscoe    Male       3900.0   44
128     Adelie  Torgersen  Female       3050.0   52
181  Chinstrap      Dream    Male       4550.0   68
157  Chinstrap      Dream  Female       3950.0   68

In [8]:
# instead of count, group_x with value + aggfunc: add group mean of body_mass_g to every row
(pt.group_x(penguins, group=['species'], v='body_mass_g', a='mean').rename(columns={'x': 'species_mean_mass'}).sample(10))

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_mean_mass
26,Adelie,Biscoe,40.6,18.6,183.0,3550.0,Male,3700.662252
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,3700.662252
33,Adelie,Dream,40.9,18.9,184.0,3900.0,Male,3700.662252
139,Adelie,Dream,39.7,17.9,193.0,4250.0,Male,3700.662252
265,Gentoo,Biscoe,43.6,13.9,217.0,4900.0,Female,5076.016260
94,Adelie,Dream,36.2,17.3,187.0,3300.0,Female,3700.662252
143,Adelie,Dream,40.7,17.0,190.0,3725.0,Male,3700.662252
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,Male,3700.662252
36,Adelie,Dream,38.8,20.0,190.0,3950.0,Male,3700.662252
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,5076.016260

In [9]:
#with dropna=False
pt.group_x(penguins, group=['species', 'sex'],dropna=False)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,n
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,73
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,73
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,73
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,6
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,73
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,5
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,58
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,61
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,58
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,61

In [10]:
#with default dropna=True
pt.group_x(penguins, group=['species', 'sex'])

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,n
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,73.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,73.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female,73.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female,73.0
...,...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female,58.0
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male,61.0
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female,58.0
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male,61.0

## `to_clip()` — copy to clipboard
`to_clip()` copies the DataFrame to the system clipboard as tab-separated text (no index). Paste directly into Excel, Google Sheets, or any text editor. Invisible in notebook output — run it and then paste.

In [11]:
# to_clip() copies the current DataFrame to clipboard — paste into Excel/Sheets
# Run this cell then Cmd+V in any spreadsheet application
pt.to_clip(pt.agg_df(pt.select(penguins, 'species', 'island', 'bill_length_mm', 'body_mass_g'), a=['mean', 'n']))

## `clean_columns()` — clean messy header names
Cleans column header names in a fixed order: `strip` -> `strip_special` -> `squeeze` -> `fill` -> `case` -> `dedupe`. Handy after loading a spreadsheet export with inconsistent spacing/casing.

In [12]:
# messy headers: leading/trailing spaces, repeated internal spaces, mixed case
messy = penguins.rename(columns={
    'species': '  Species  ',
    'island': 'Island   Name',
    'body_mass_g': 'Body Mass (g)',
})

pt.cols(pt.clean_columns(messy, strip=True, squeeze=True, strip_special=True, fill='_', case='lower'), ascending=None)

['species',
 'island_name',
 'bill_length_mm',
 'bill_depth_mm',
 'flipper_length_mm',
 'body_mass_g',
 'sex']

In [13]:
# Proper/Title Case, no fill — spaces in header names are left alone
pt.cols(pt.clean_columns(penguins, case='proper'), ascending=None)

['Species',
 'Island',
 'Bill_Length_Mm',
 'Bill_Depth_Mm',
 'Flipper_Length_Mm',
 'Body_Mass_G',
 'Sex']

## `replace_values()` — replace values, whole-cell or substring
Wraps pandas `replace()`. `exact=True` (default) only replaces a cell whose entire value matches a key exactly; `exact=False` replaces a key anywhere it occurs as a substring, leaving the rest of the cell untouched. Optionally scope to specific columns with `c=`. Parameter names (`v=`, `c=`, `exact=`) match the `-replace_values` CLI flag.

In [14]:
# exact=True (default): only cells that equal 'Adelie'/'Male' exactly are replaced
(pt.select(pt.replace_values(penguins, {'Adelie': 'Adelie (renamed)', 'Male': 'M'}), 'species', 'sex').drop_duplicates())

              species     sex
0    Adelie (renamed)       M
1    Adelie (renamed)  Female
3    Adelie (renamed)     NaN
152         Chinstrap  Female
153         Chinstrap       M
220            Gentoo  Female
221            Gentoo       M
246            Gentoo     NaN

In [15]:
# c= restricts the replace to specific columns — 'island' untouched even though
# it never contained 'Male' anyway, this shows the scoping mechanism itself
(pt.select(pt.replace_values(penguins, {'Male': 'M', 'Female': 'F'}, c='sex'), 'island', 'sex').drop_duplicates())

        island  sex
0    Torgersen    M
1    Torgersen    F
3    Torgersen  NaN
20      Biscoe    F
21      Biscoe    M
30       Dream    F
31       Dream    M
47       Dream  NaN
246     Biscoe  NaN

In [16]:
# exact=False: substring match anywhere in the cell, rest of the cell untouched
import pandas as pd

notes = pd.DataFrame({'note': ['a magician performed', 'not a magician exactly', 'no match here']})
pt.replace_values(notes, {'a magician': 'the magic'}, exact=False)

                    note
0    the magic performed
1  not the magic exactly
2          no match here