# `filter` — Reference

`filter` filters a DataFrame using intuitive keyword arguments, CLI-style string expressions, plain dictionaries, or any combination of the three.

### Calling Styles

`filter` supports multiple flexible calling styles to fit interactive analysis, programmatic pipelines, and column names with spaces:

- **Keyword arguments**: `df.filter(species='Adelie', body_mass_g='> 5000')`
- **String expressions** (matches CLI `-filter` syntax; handles spaces directly): `df.filter("bill length mm > 40, species = 'Adelie'")`
- **Plain dictionaries** (ideal for dynamic keys or columns with spaces): `df.filter({"bill length mm": "> 40", "species": "Adelie"})`
- **Mixed calling**: `df.filter("bill length mm > 40", {"island": "Biscoe"}, species="Gentoo")`
- **Library function**: `pt.filter(df, species='Adelie', body_mass_g='> 5000')`

### Supported Condition Types

| Condition | Example Syntax | Meaning |
|---|---|---|
| Equality | `species='Adelie'` or `"species = Adelie"` | exact match |
| Membership | `species=['Adelie', 'Gentoo']` | in list |
| Tuple membership | `species=('in', ['Adelie', 'Gentoo'])` | in list |
| Exclusion | `sex=('not in', ['Male'])` | not in list |
| Comparison (operator) | `body_mass_g='> 5000'` or `body_mass_g=('>', 5000)` | `>`, `>=`, `<`, `<=`, `==`, `!=` |
| Open interval | `body_mass_g='(3500,4500)'` | `3500 < x < 4500` |
| Half-open interval | `bill_length_mm='[40,50)'` | `40 <= x < 50` |
| Closed interval | `body_mass_g='[3500,4000]'` | `3500 <= x <= 4000` |
| String matching | `species=('startswith', 'Ad')` | `startswith`, `endswith`, `contains`, `regex` |
| Multiple prefixes/suffixes | `species=('startswith', ['Ad', 'Ge'])` | matches any prefix/suffix in list/tuple |
| Null check | `sex=('isna',)` / `sex=('notna',)` | missing / non-missing (unary tuple) |
| Columns with spaces | `"bill length mm > 40"` or `{"bill length mm": "> 40"}` | spaces handled without dict unpacking |
| Same-column bounds | `"mass > 3000, mass < 5000"` or `"mass > 3000", "mass < 5000"` | multiple conditions on same column |

---

In [1]:
import sys, os
_src = os.path.abspath(os.path.join(os.getcwd(), '..', '..', 'src'))
if not os.path.exists(_src): _src = os.path.abspath(os.path.join(os.getcwd(), '..', 'src'))
if _src not in sys.path: sys.path.insert(0, _src)

import pytae as pt

penguins = pt.sample_data['penguins']
tips = pt.sample_data['tips']
titanic = pt.sample_data['titanic']

## Flexible calling styles: kwargs, string expressions, and dictionaries

`filter()` accepts conditions as keyword arguments, string expressions matching the CLI `-filter` syntax, plain dictionaries, or any mix of the three. Both direct method chaining (`df.filter(...)`) and the top-level library verb (`pt.filter(df, ...)`) are supported.

In [2]:
# 1. Keyword arguments — clean and pythonic
(
    penguins
    .filter(species='Adelie', island='Dream')
    .sample(10)
)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie  ┆ Dream  ┆ 39.5           ┆ 17.8          ┆ 188.0             ┆ 3300.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 42.2           ┆ 18.5          ┆ 180.0             ┆ 3550.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 36.0           ┆ 17.9          ┆ 190.0             ┆ 3450.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 41.3           ┆ 20.3          ┆ 194.0             ┆ 3550.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 35.7           ┆ 18.0          ┆ 202.0             ┆ 3550.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 40.3           ┆ 18.5          ┆ 196.0             ┆ 4350.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 43.2           ┆ 18.5          ┆ 192.0             ┆ 4100.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 40.6           ┆ 17.2          ┆ 187.0             ┆ 3475.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 37.3           ┆ 16.8          ┆ 192.0             ┆ 3000.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 36.6           ┆ 18.4          ┆ 184.0             ┆ 3475.0      ┆ Female │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [3]:
# 2. String expressions — matches pytae CLI -qry syntax; supports comma-separated conditions
(
    penguins
    .filter("species = 'Adelie', body_mass_g > 4000")
    .sample(10)
)

shape: (10, 7)
┌─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬──────┐
│ species ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex  │
│ ---     ┆ ---       ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---  │
│ str     ┆ str       ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str  │
╞═════════╪═══════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪══════╡
│ Adelie  ┆ Torgersen ┆ 39.2           ┆ 19.6          ┆ 195.0             ┆ 4675.0      ┆ Male │
│ Adelie  ┆ Dream     ┆ 44.1           ┆ 19.7          ┆ 196.0             ┆ 4400.0      ┆ Male │
│ Adelie  ┆ Dream     ┆ 39.6           ┆ 18.8          ┆ 190.0             ┆ 4600.0      ┆ Male │
│ Adelie  ┆ Biscoe    ┆ 42.0           ┆ 19.5          ┆ 200.0             ┆ 4050.0      ┆ Male │
│ Adelie  ┆ Biscoe    ┆ 41.1           ┆ 18.2          ┆ 192.0             ┆ 4050.0      ┆ Male │
│ Adelie  ┆ Torgersen ┆ 42.8           ┆ 18.5          ┆ 195.0             ┆ 4250.0      ┆ Male │
│ Adelie  ┆ Torgersen ┆ 42.9           ┆ 17.6          ┆ 196.0             ┆ 4700.0      ┆ Male │
│ Adelie  ┆ Biscoe    ┆ 37.8           ┆ 20.0          ┆ 190.0             ┆ 4250.0      ┆ Male │
│ Adelie  ┆ Biscoe    ┆ 42.2           ┆ 19.5          ┆ 197.0             ┆ 4275.0      ┆ Male │
│ Adelie  ┆ Dream     ┆ 39.7           ┆ 17.9          ┆ 193.0             ┆ 4250.0      ┆ Male │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴──────┘

In [4]:
# 3. Plain dictionaries — useful for programmatic pipelines or dynamic key mapping
(
    penguins
    .filter({"species": "Adelie", "island": "Dream"})
    .sample(10)
)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie  ┆ Dream  ┆ 37.6           ┆ 19.3          ┆ 181.0             ┆ 3300.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 37.0           ┆ 16.9          ┆ 185.0             ┆ 3000.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 41.1           ┆ 19.0          ┆ 182.0             ┆ 3425.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 41.3           ┆ 20.3          ┆ 194.0             ┆ 3550.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 36.2           ┆ 17.3          ┆ 187.0             ┆ 3300.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 38.1           ┆ 17.6          ┆ 187.0             ┆ 3425.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 41.1           ┆ 17.5          ┆ 190.0             ┆ 3900.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 39.0           ┆ 18.7          ┆ 185.0             ┆ 3650.0      ┆ Male   │
│ Adelie  ┆ Dream  ┆ 36.0           ┆ 17.8          ┆ 195.0             ┆ 3450.0      ┆ Female │
│ Adelie  ┆ Dream  ┆ 36.0           ┆ 17.1          ┆ 187.0             ┆ 3700.0      ┆ Female │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [5]:
# 4. Mixed calling — combine string expressions, dicts, and kwargs in a single call
(
    penguins
    .filter("body_mass_g > 4000", {"island": "Biscoe"}, sex="Female")
    .sample(10)
)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Gentoo  ┆ Biscoe ┆ 46.2           ┆ 14.5          ┆ 209.0             ┆ 4800.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 45.1           ┆ 14.5          ┆ 207.0             ┆ 5050.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 45.5           ┆ 13.9          ┆ 210.0             ┆ 4200.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 45.7           ┆ 13.9          ┆ 214.0             ┆ 4400.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 45.8           ┆ 14.2          ┆ 219.0             ┆ 4700.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 47.7           ┆ 15.0          ┆ 216.0             ┆ 4750.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 43.4           ┆ 14.4          ┆ 218.0             ┆ 4600.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 43.5           ┆ 15.2          ┆ 213.0             ┆ 4650.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 47.2           ┆ 13.7          ┆ 214.0             ┆ 4925.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 45.2           ┆ 14.8          ┆ 212.0             ┆ 5200.0      ┆ Female │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [6]:
# 5. Top-level function pt.filter(df, ...) — works identically to DataFrame methods
pt.filter(penguins, species="Gentoo", body_mass_g="> 5000").sample(10)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬──────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex  │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---  │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str  │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪══════╡
│ Gentoo  ┆ Biscoe ┆ 46.7           ┆ 15.3          ┆ 219.0             ┆ 5200.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 48.4           ┆ 14.6          ┆ 213.0             ┆ 5850.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.3           ┆ 15.7          ┆ 217.0             ┆ 5850.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 44.4           ┆ 17.3          ┆ 219.0             ┆ 5250.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 45.0           ┆ 15.4          ┆ 220.0             ┆ 5050.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.5           ┆ 16.2          ┆ 229.0             ┆ 5800.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 48.6           ┆ 16.0          ┆ 230.0             ┆ 5800.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 50.8           ┆ 15.7          ┆ 226.0             ┆ 5200.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.8           ┆ 15.9          ┆ 229.0             ┆ 5950.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 55.1           ┆ 16.0          ┆ 230.0             ┆ 5850.0      ┆ Male │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴──────┘

## Column names with spaces — bracket notation `[col]`

When columns have spaces (like `'bill length mm'`), enclose them in square brackets `[col]` inside string expressions. This avoids keyword argument restrictions and dictionary unpacking entirely.

In [7]:
# DataFrame with spaces in column names
penguins_spaces = penguins.rename(
    columns={'bill_length_mm': 'bill length mm', 'body_mass_g': 'body mass g'}
)

# String expressions with brackets handle spaced column names cleanly:
(
    penguins_spaces
    .filter("[bill length mm] > 45", "[body mass g] > 4000")
    .sample(10)
)

shape: (10, 7)
┌───────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species   ┆ island ┆ bill length mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body mass g ┆ sex    │
│ ---       ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str       ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═══════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Chinstrap ┆ Dream  ┆ 46.0           ┆ 18.9          ┆ 195.0             ┆ 4150.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 52.8           ┆ 20.0          ┆ 205.0             ┆ 4550.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 53.5           ┆ 19.9          ┆ 205.0             ┆ 4500.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 47.6           ┆ 14.5          ┆ 215.0             ┆ 5400.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 46.2           ┆ 14.5          ┆ 209.0             ┆ 4800.0      ┆ Female │
│ Gentoo    ┆ Biscoe ┆ 50.5           ┆ 15.9          ┆ 225.0             ┆ 5400.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 45.8           ┆ 14.2          ┆ 219.0             ┆ 4700.0      ┆ Female │
│ Gentoo    ┆ Biscoe ┆ 50.7           ┆ 15.0          ┆ 223.0             ┆ 5550.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 51.1           ┆ 16.5          ┆ 225.0             ┆ 5250.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 50.5           ┆ 15.2          ┆ 216.0             ┆ 5000.0      ┆ Female │
└───────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [8]:
# DataFrame with spaces in column names
penguins_spaces = penguins.rename(
    columns={'bill_length_mm': 'bill length mm', 'body_mass_g': 'body mass g'}
)

# String expressions with brackets handle spaced column names cleanly:
(
    penguins_spaces
    .filter("[bill length mm] > 45", "[body mass g] > 4000")
    .sample(10)
)

shape: (10, 7)
┌───────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species   ┆ island ┆ bill length mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body mass g ┆ sex    │
│ ---       ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str       ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═══════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Chinstrap ┆ Dream  ┆ 49.2           ┆ 18.2          ┆ 195.0             ┆ 4400.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 48.4           ┆ 14.6          ┆ 213.0             ┆ 5850.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 48.4           ┆ 16.3          ┆ 220.0             ┆ 5400.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 46.6           ┆ 14.2          ┆ 210.0             ┆ 4850.0      ┆ Female │
│ Gentoo    ┆ Biscoe ┆ 50.7           ┆ 15.0          ┆ 223.0             ┆ 5550.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 47.7           ┆ 15.0          ┆ 216.0             ┆ 4750.0      ┆ Female │
│ Gentoo    ┆ Biscoe ┆ 47.4           ┆ 14.6          ┆ 212.0             ┆ 4725.0      ┆ Female │
│ Gentoo    ┆ Biscoe ┆ 51.3           ┆ 14.2          ┆ 218.0             ┆ 5300.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 52.2           ┆ 17.1          ┆ 228.0             ┆ 5400.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 50.8           ┆ 15.7          ┆ 226.0             ┆ 5200.0      ┆ Male   │
└───────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

## Equality and multi-value filters

In [9]:
# Single equality — keep only Dream island
(
    penguins
    .filter(island='Dream')
    .sample(10)
)

shape: (10, 7)
┌───────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species   ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str       ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═══════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Dream  ┆ 40.6           ┆ 17.2          ┆ 187.0             ┆ 3475.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 52.7           ┆ 19.8          ┆ 197.0             ┆ 3725.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 45.9           ┆ 17.1          ┆ 190.0             ┆ 3575.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 46.4           ┆ 18.6          ┆ 190.0             ┆ 3450.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 46.9           ┆ 16.6          ┆ 192.0             ┆ 2700.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 50.1           ┆ 17.9          ┆ 190.0             ┆ 3400.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 51.4           ┆ 19.0          ┆ 201.0             ┆ 3950.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 50.2           ┆ 18.8          ┆ 202.0             ┆ 3800.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 51.9           ┆ 19.5          ┆ 206.0             ┆ 3950.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 49.6           ┆ 18.2          ┆ 193.0             ┆ 3775.0      ┆ Male   │
└───────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [10]:
# List — keep Adelie and Chinstrap, aggregate per species + island
# Kwargs accept a list directly:
(
    penguins
    .filter(species=['Adelie', 'Chinstrap'])
    .select('species', 'island', 'body_mass_g')
    .by('species', 'island')
    .agg(a=['mean', 'n'])
)

shape: (4, 4)
┌───────────┬───────────┬─────┬─────────────┐
│ species   ┆ island    ┆ n   ┆ body_mass_g │
│ ---       ┆ ---       ┆ --- ┆ ---         │
│ str       ┆ str       ┆ i64 ┆ f64         │
╞═══════════╪═══════════╪═════╪═════════════╡
│ Adelie    ┆ Biscoe    ┆ 44  ┆ 3709.659091 │
│ Adelie    ┆ Dream     ┆ 56  ┆ 3688.392857 │
│ Adelie    ┆ Torgersen ┆ 52  ┆ 3706.372549 │
│ Chinstrap ┆ Dream     ┆ 68  ┆ 3733.088235 │
└───────────┴───────────┴─────┴─────────────┘

In [11]:
# 'not in' — exclude Male penguins via kwargs
(
    penguins
    .filter(sex=('not in', ['Male']))
    .sample(10)
)

shape: (10, 7)
┌───────────┬───────────┬────────────────┬───────────────┬──────────────────┬─────────────┬────────┐
│ species   ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_m ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---       ┆ ---            ┆ ---           ┆ m                ┆ ---         ┆ ---    │
│ str       ┆ str       ┆ f64            ┆ f64           ┆ ---              ┆ f64         ┆ str    │
│           ┆           ┆                ┆               ┆ f64              ┆             ┆        │
╞═══════════╪═══════════╪════════════════╪═══════════════╪══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Torgersen ┆ 38.7           ┆ 19.0          ┆ 195.0            ┆ 3450.0      ┆ Female │
│ Adelie    ┆ Biscoe    ┆ 37.9           ┆ 18.6          ┆ 172.0            ┆ 3150.0      ┆ Female │
│ Adelie    ┆ Dream     ┆ 36.0           ┆ 17.9          ┆ 190.0            ┆ 3450.0      ┆ Female │
│ Adelie    ┆ Biscoe    ┆ 36.4           ┆ 17.1          ┆ 184.0            ┆ 2850.0      ┆ Female │
│ Adelie    ┆ Biscoe    ┆ 35.0           ┆ 17.9          ┆ 192.0            ┆ 3725.0      ┆ Female │
│ Adelie    ┆ Biscoe    ┆ 39.6           ┆ 20.7          ┆ 191.0            ┆ 3900.0      ┆ Female │
│ Adelie    ┆ Dream     ┆ 40.2           ┆ 17.1          ┆ 193.0            ┆ 3400.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 45.5           ┆ 17.0          ┆ 196.0            ┆ 3500.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 45.3           ┆ 13.7          ┆ 210.0            ┆ 4300.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 46.6           ┆ 14.2          ┆ 210.0            ┆ 4850.0      ┆ Female │
└───────────┴───────────┴────────────────┴───────────────┴──────────────────┴─────────────┴────────┘

## Comparison operators

Comparison filters can be written as string expressions (`body_mass_g="> 5000"`) or operator tuples (`body_mass_g=('>', 5000)`).
Supported comparison operators: `>`, `>=`, `<`, `<=`, `==`, `!=`.

In [12]:
# Filter penguins with body mass greater than 5000g (string operator)
(
    penguins
    .filter(body_mass_g='> 5000')
    .sample(10)
)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬──────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex  │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---  │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str  │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪══════╡
│ Gentoo  ┆ Biscoe ┆ 50.0           ┆ 16.3          ┆ 230.0             ┆ 5700.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 50.0           ┆ 15.2          ┆ 218.0             ┆ 5700.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 46.3           ┆ 15.8          ┆ 215.0             ┆ 5050.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 45.0           ┆ 15.4          ┆ 220.0             ┆ 5050.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 46.2           ┆ 14.9          ┆ 221.0             ┆ 5300.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 50.7           ┆ 15.0          ┆ 223.0             ┆ 5550.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 52.5           ┆ 15.6          ┆ 221.0             ┆ 5450.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 50.0           ┆ 15.9          ┆ 224.0             ┆ 5350.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 52.1           ┆ 17.0          ┆ 230.0             ┆ 5550.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 51.1           ┆ 16.5          ┆ 225.0             ┆ 5250.0      ┆ Male │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴──────┘

In [13]:
# Tuple operator syntax: ('>', 5000)
(
    penguins
    .filter(body_mass_g=('>', 5000))
    .sample(10)
)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬──────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex  │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---  │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str  │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪══════╡
│ Gentoo  ┆ Biscoe ┆ 48.4           ┆ 14.6          ┆ 213.0             ┆ 5850.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 50.0           ┆ 15.3          ┆ 220.0             ┆ 5550.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 59.6           ┆ 17.0          ┆ 230.0             ┆ 6050.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 48.7           ┆ 15.7          ┆ 208.0             ┆ 5350.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.6           ┆ 16.0          ┆ 225.0             ┆ 5700.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 50.5           ┆ 15.9          ┆ 222.0             ┆ 5550.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 45.0           ┆ 15.4          ┆ 220.0             ┆ 5050.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.5           ┆ 16.1          ┆ 224.0             ┆ 5650.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.1           ┆ 15.0          ┆ 228.0             ┆ 5500.0      ┆ Male │
│ Gentoo  ┆ Biscoe ┆ 49.8           ┆ 15.9          ┆ 229.0             ┆ 5950.0      ┆ Male │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴──────┘

In [14]:
# Combine multiple column conditions in one qry call
# Gentoo females with large bills — multi-condition kwargs:
(
    penguins
    .filter(species='Gentoo', sex='Female', bill_length_mm='>= 45')
    .select('species', 'island', 'sex', 'bill_length_mm', 'body_mass_g')
    .sample(10)
)

shape: (10, 5)
┌─────────┬────────┬────────┬────────────────┬─────────────┐
│ species ┆ island ┆ sex    ┆ bill_length_mm ┆ body_mass_g │
│ ---     ┆ ---    ┆ ---    ┆ ---            ┆ ---         │
│ str     ┆ str    ┆ str    ┆ f64            ┆ f64         │
╞═════════╪════════╪════════╪════════════════╪═════════════╡
│ Gentoo  ┆ Biscoe ┆ Female ┆ 46.1           ┆ 4500.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 45.1           ┆ 5000.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 46.6           ┆ 4850.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 46.4           ┆ 4700.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 45.2           ┆ 4750.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 49.1           ┆ 4625.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 47.5           ┆ 4875.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 46.2           ┆ 4375.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 47.2           ┆ 4925.0      │
│ Gentoo  ┆ Biscoe ┆ Female ┆ 46.8           ┆ 4850.0      │
└─────────┴────────┴────────┴────────────────┴─────────────┘

## Interval notation
String intervals let you filter a range on the same column without chaining two `.filter()` calls.
`(` / `)` = exclusive bound, `[` / `]` = inclusive bound.

In [15]:
# Open interval — strictly between 3500 and 4500 g via kwargs:
(
    penguins
    .filter(body_mass_g='(3500,4500)')
    .sample(10)
)

shape: (10, 7)
┌───────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species   ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str       ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═══════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Biscoe ┆ 40.6           ┆ 18.8          ┆ 193.0             ┆ 3800.0      ┆ Male   │
│ Adelie    ┆ Dream  ┆ 41.5           ┆ 18.5          ┆ 201.0             ┆ 4000.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 46.0           ┆ 18.9          ┆ 195.0             ┆ 4150.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 49.2           ┆ 18.2          ┆ 195.0             ┆ 4400.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 50.6           ┆ 19.4          ┆ 193.0             ┆ 3800.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 47.5           ┆ 16.8          ┆ 199.0             ┆ 3900.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 49.0           ┆ 19.5          ┆ 210.0             ┆ 3950.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 50.9           ┆ 19.1          ┆ 196.0             ┆ 3550.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 50.8           ┆ 18.5          ┆ 201.0             ┆ 4450.0      ┆ Male   │
│ Gentoo    ┆ Biscoe ┆ 46.2           ┆ 14.1          ┆ 217.0             ┆ 4375.0      ┆ Female │
└───────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [16]:
# Half-open interval — bill_length_mm >= 40 and < 50
(
    penguins
    .filter(bill_length_mm='[40,50)')
    .sample(10)
)

shape: (10, 7)
┌───────────┬───────────┬────────────────┬───────────────┬──────────────────┬─────────────┬────────┐
│ species   ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_m ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---       ┆ ---            ┆ ---           ┆ m                ┆ ---         ┆ ---    │
│ str       ┆ str       ┆ f64            ┆ f64           ┆ ---              ┆ f64         ┆ str    │
│           ┆           ┆                ┆               ┆ f64              ┆             ┆        │
╞═══════════╪═══════════╪════════════════╪═══════════════╪══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Torgersen ┆ 42.0           ┆ 20.2          ┆ 190.0            ┆ 4250.0      ┆ null   │
│ Adelie    ┆ Dream     ┆ 42.3           ┆ 21.2          ┆ 191.0            ┆ 4150.0      ┆ Male   │
│ Adelie    ┆ Torgersen ┆ 43.1           ┆ 19.2          ┆ 197.0            ┆ 3500.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 45.2           ┆ 17.8          ┆ 198.0            ┆ 3950.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 46.1           ┆ 18.2          ┆ 178.0            ┆ 3250.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 46.6           ┆ 17.8          ┆ 193.0            ┆ 3800.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 49.0           ┆ 19.6          ┆ 212.0            ┆ 4300.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 42.5           ┆ 17.3          ┆ 187.0            ┆ 3350.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 46.5           ┆ 14.5          ┆ 213.0            ┆ 4400.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 47.2           ┆ 13.7          ┆ 214.0            ┆ 4925.0      ┆ Female │
└───────────┴───────────┴────────────────┴───────────────┴──────────────────┴─────────────┴────────┘

In [17]:
# Closed interval — body_mass_g between 3500 and 4000 inclusive
(
    penguins
    .filter(body_mass_g='[3500,4000]')
    .sample(10)
)

shape: (10, 7)
┌───────────┬───────────┬────────────────┬───────────────┬──────────────────┬─────────────┬────────┐
│ species   ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_m ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---       ┆ ---            ┆ ---           ┆ m                ┆ ---         ┆ ---    │
│ str       ┆ str       ┆ f64            ┆ f64           ┆ ---              ┆ f64         ┆ str    │
│           ┆           ┆                ┆               ┆ f64              ┆             ┆        │
╞═══════════╪═══════════╪════════════════╪═══════════════╪══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Torgersen ┆ 36.6           ┆ 17.8          ┆ 185.0            ┆ 3700.0      ┆ Female │
│ Adelie    ┆ Biscoe    ┆ 38.2           ┆ 18.1          ┆ 185.0            ┆ 3950.0      ┆ Male   │
│ Adelie    ┆ Biscoe    ┆ 35.3           ┆ 18.9          ┆ 187.0            ┆ 3800.0      ┆ Female │
│ Adelie    ┆ Dream     ┆ 38.8           ┆ 20.0          ┆ 190.0            ┆ 3950.0      ┆ Male   │
│ Adelie    ┆ Biscoe    ┆ 37.6           ┆ 17.0          ┆ 185.0            ┆ 3600.0      ┆ Female │
│ Adelie    ┆ Torgersen ┆ 40.9           ┆ 16.8          ┆ 191.0            ┆ 3700.0      ┆ Female │
│ Adelie    ┆ Dream     ┆ 41.1           ┆ 17.5          ┆ 190.0            ┆ 3900.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 51.3           ┆ 19.2          ┆ 193.0            ┆ 3650.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 52.7           ┆ 19.8          ┆ 197.0            ┆ 3725.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 49.8           ┆ 17.3          ┆ 198.0            ┆ 3675.0      ┆ Female │
└───────────┴───────────┴────────────────┴───────────────┴──────────────────┴─────────────┴────────┘

In [18]:
# Interval notation also works on STRING columns — alphabetical comparison
# 'island' values: Biscoe, Dream, Torgersen — (Biscoe, Dream] means Dream only
(
    penguins
    .filter(island='(Biscoe,Dream]')
    .sample()
)

shape: (5, 7)
┌───────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species   ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str       ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═══════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Dream  ┆ 39.2           ┆ 21.1          ┆ 196.0             ┆ 4150.0      ┆ Male   │
│ Adelie    ┆ Dream  ┆ 36.0           ┆ 17.9          ┆ 190.0             ┆ 3450.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 43.2           ┆ 16.6          ┆ 187.0             ┆ 2900.0      ┆ Female │
│ Chinstrap ┆ Dream  ┆ 49.7           ┆ 18.6          ┆ 195.0             ┆ 3600.0      ┆ Male   │
│ Chinstrap ┆ Dream  ┆ 50.8           ┆ 18.5          ┆ 201.0             ┆ 4450.0      ┆ Male   │
└───────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

## String matching and null checks
`startswith`/`endswith`/`contains`/`regex` use pandas' `.str` accessor (missing values never match, `na=False`). `contains`/`regex` both search anywhere in the string (like `re.search`) — `regex` is just `contains` with `regex=True`.

`startswith` and `endswith` also accept a list or tuple of multiple prefixes/suffixes. `isna`/`notna` are one-element tuples since they take no value.

In [19]:
# species starting with 'Ad' — same idea for endswith/contains
(
    penguins
    .filter(species=('startswith', 'Ad'))
    .sample(10)
)

shape: (10, 7)
┌─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---       ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str       ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═════════╪═══════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie  ┆ Torgersen ┆ 39.5           ┆ 17.4          ┆ 186.0             ┆ 3800.0      ┆ Female │
│ Adelie  ┆ Torgersen ┆ 37.8           ┆ 17.3          ┆ 180.0             ┆ 3700.0      ┆ null   │
│ Adelie  ┆ Dream     ┆ 40.9           ┆ 18.9          ┆ 184.0             ┆ 3900.0      ┆ Male   │
│ Adelie  ┆ Dream     ┆ 36.4           ┆ 17.0          ┆ 195.0             ┆ 3325.0      ┆ Female │
│ Adelie  ┆ Dream     ┆ 37.6           ┆ 19.3          ┆ 181.0             ┆ 3300.0      ┆ Female │
│ Adelie  ┆ Dream     ┆ 37.0           ┆ 16.9          ┆ 185.0             ┆ 3000.0      ┆ Female │
│ Adelie  ┆ Biscoe    ┆ 41.6           ┆ 18.0          ┆ 192.0             ┆ 3950.0      ┆ Male   │
│ Adelie  ┆ Dream     ┆ 36.2           ┆ 17.3          ┆ 187.0             ┆ 3300.0      ┆ Female │
│ Adelie  ┆ Biscoe    ┆ 38.1           ┆ 16.5          ┆ 198.0             ┆ 3825.0      ┆ Female │
│ Adelie  ┆ Torgersen ┆ 41.5           ┆ 18.3          ┆ 195.0             ┆ 4300.0      ┆ Male   │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [20]:
# Multiple prefixes: species starting with 'Ad' OR 'Ge'
(
    penguins
    .filter(species=('startswith', ['Ad', 'Ge']))
    .sample(10)
)

shape: (0, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬─────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ --- │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪═════╡
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴─────┘

In [21]:
# regex, search-anywhere (like re.search) — species containing a repeated 'o'
(
    penguins
    .filter(species=('regex', r'oo'))
    .sample(10)
)

shape: (10, 7)
┌─────────┬────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---    ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str    ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═════════╪════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Gentoo  ┆ Biscoe ┆ 42.0           ┆ 13.5          ┆ 210.0             ┆ 4150.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 44.0           ┆ 13.6          ┆ 208.0             ┆ 4350.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 49.6           ┆ 15.0          ┆ 216.0             ┆ 4750.0      ┆ Male   │
│ Gentoo  ┆ Biscoe ┆ 45.2           ┆ 15.8          ┆ 215.0             ┆ 5300.0      ┆ Male   │
│ Gentoo  ┆ Biscoe ┆ 49.8           ┆ 16.8          ┆ 230.0             ┆ 5700.0      ┆ Male   │
│ Gentoo  ┆ Biscoe ┆ 47.5           ┆ 14.2          ┆ 209.0             ┆ 4600.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 51.1           ┆ 16.3          ┆ 220.0             ┆ 6000.0      ┆ Male   │
│ Gentoo  ┆ Biscoe ┆ 45.2           ┆ 13.8          ┆ 215.0             ┆ 4750.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 43.4           ┆ 14.4          ┆ 218.0             ┆ 4600.0      ┆ Female │
│ Gentoo  ┆ Biscoe ┆ 41.7           ┆ 14.7          ┆ 210.0             ┆ 4700.0      ┆ Female │
└─────────┴────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [22]:
# isna/notna — rows with a missing 'sex' value (one-element tuple, no value needed)
(
    penguins
    .filter(sex=('isna',))
)

shape: (11, 7)
┌─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬──────┐
│ species ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex  │
│ ---     ┆ ---       ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---  │
│ str     ┆ str       ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str  │
╞═════════╪═══════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪══════╡
│ Adelie  ┆ Torgersen ┆ null           ┆ null          ┆ null              ┆ null        ┆ null │
│ Adelie  ┆ Torgersen ┆ 34.1           ┆ 18.1          ┆ 193.0             ┆ 3475.0      ┆ null │
│ Adelie  ┆ Torgersen ┆ 42.0           ┆ 20.2          ┆ 190.0             ┆ 4250.0      ┆ null │
│ Adelie  ┆ Torgersen ┆ 37.8           ┆ 17.1          ┆ 186.0             ┆ 3300.0      ┆ null │
│ Adelie  ┆ Torgersen ┆ 37.8           ┆ 17.3          ┆ 180.0             ┆ 3700.0      ┆ null │
│ …       ┆ …         ┆ …              ┆ …             ┆ …                 ┆ …           ┆ …    │
│ Gentoo  ┆ Biscoe    ┆ 44.5           ┆ 14.3          ┆ 216.0             ┆ 4100.0      ┆ null │
│ Gentoo  ┆ Biscoe    ┆ 46.2           ┆ 14.4          ┆ 214.0             ┆ 4650.0      ┆ null │
│ Gentoo  ┆ Biscoe    ┆ 47.3           ┆ 13.8          ┆ 216.0             ┆ 4725.0      ┆ null │
│ Gentoo  ┆ Biscoe    ┆ 44.5           ┆ 15.7          ┆ 217.0             ┆ 4875.0      ┆ null │
│ Gentoo  ┆ Biscoe    ┆ null           ┆ null          ┆ null              ┆ null        ┆ null │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴──────┘

## Multiple conditions on the same column

Because Python keyword arguments must have unique names, you cannot pass `bill_length_mm='> 40', bill_length_mm='< 50'` in kwargs. With `filter()`, you have multiple intuitive solutions:

1. **Comma-separated string expression**: `"bill_length_mm > 40, bill_length_mm < 50"`
2. **Multiple positional string arguments**: `"bill_length_mm > 40", "bill_length_mm < 50"`
3. **Interval notation**: `bill_length_mm='[40,50)'`
4. **Chained `.filter()` calls**: `.filter(bill_length_mm='> 40').filter(bill_length_mm='< 50')`

In [23]:
# Comma-separated string expression on the same column:
(
    penguins
    .filter("bill_length_mm > 40, bill_length_mm < 50")
    .sample(10)
)

shape: (10, 7)
┌─────────┬───────────┬────────────────┬───────────────┬───────────────────┬─────────────┬────────┐
│ species ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_mm ┆ body_mass_g ┆ sex    │
│ ---     ┆ ---       ┆ ---            ┆ ---           ┆ ---               ┆ ---         ┆ ---    │
│ str     ┆ str       ┆ f64            ┆ f64           ┆ f64               ┆ f64         ┆ str    │
╞═════════╪═══════════╪════════════════╪═══════════════╪═══════════════════╪═════════════╪════════╡
│ Adelie  ┆ Torgersen ┆ 41.8           ┆ 19.4          ┆ 198.0             ┆ 4450.0      ┆ Male   │
│ Adelie  ┆ Torgersen ┆ 42.8           ┆ 18.5          ┆ 195.0             ┆ 4250.0      ┆ Male   │
│ Adelie  ┆ Dream     ┆ 43.2           ┆ 18.5          ┆ 192.0             ┆ 4100.0      ┆ Male   │
│ Gentoo  ┆ Biscoe    ┆ 46.5           ┆ 14.5          ┆ 213.0             ┆ 4400.0      ┆ Female │
│ Gentoo  ┆ Biscoe    ┆ 44.9           ┆ 13.3          ┆ 213.0             ┆ 5100.0      ┆ Female │
│ Gentoo  ┆ Biscoe    ┆ 46.2           ┆ 14.4          ┆ 214.0             ┆ 4650.0      ┆ null   │
│ Gentoo  ┆ Biscoe    ┆ 46.4           ┆ 15.6          ┆ 221.0             ┆ 5000.0      ┆ Male   │
│ Gentoo  ┆ Biscoe    ┆ 44.5           ┆ 14.7          ┆ 214.0             ┆ 4850.0      ┆ Female │
│ Gentoo  ┆ Biscoe    ┆ 48.5           ┆ 15.0          ┆ 219.0             ┆ 4850.0      ┆ Female │
│ Gentoo  ┆ Biscoe    ┆ 47.3           ┆ 13.8          ┆ 216.0             ┆ 4725.0      ┆ null   │
└─────────┴───────────┴────────────────┴───────────────┴───────────────────┴─────────────┴────────┘

In [24]:
# Multiple string arguments:
(
    penguins
    .filter("bill_length_mm > 40", "bill_length_mm < 50")
    .sample(10)
)

shape: (10, 7)
┌───────────┬───────────┬────────────────┬───────────────┬──────────────────┬─────────────┬────────┐
│ species   ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_m ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---       ┆ ---            ┆ ---           ┆ m                ┆ ---         ┆ ---    │
│ str       ┆ str       ┆ f64            ┆ f64           ┆ ---              ┆ f64         ┆ str    │
│           ┆           ┆                ┆               ┆ f64              ┆             ┆        │
╞═══════════╪═══════════╪════════════════╪═══════════════╪══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Torgersen ┆ 41.8           ┆ 19.4          ┆ 198.0            ┆ 4450.0      ┆ Male   │
│ Adelie    ┆ Dream     ┆ 40.3           ┆ 18.5          ┆ 196.0            ┆ 4350.0      ┆ Male   │
│ Adelie    ┆ Biscoe    ┆ 42.7           ┆ 18.3          ┆ 196.0            ┆ 4075.0      ┆ Male   │
│ Adelie    ┆ Torgersen ┆ 40.2           ┆ 17.0          ┆ 176.0            ┆ 3450.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 46.5           ┆ 17.9          ┆ 192.0            ┆ 3500.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 49.3           ┆ 19.9          ┆ 203.0            ┆ 4050.0      ┆ Male   │
│ Gentoo    ┆ Biscoe    ┆ 49.2           ┆ 15.2          ┆ 221.0            ┆ 6300.0      ┆ Male   │
│ Gentoo    ┆ Biscoe    ┆ 48.2           ┆ 14.3          ┆ 210.0            ┆ 4600.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 44.9           ┆ 13.8          ┆ 212.0            ┆ 4750.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 47.2           ┆ 15.5          ┆ 215.0            ┆ 4975.0      ┆ Female │
└───────────┴───────────┴────────────────┴───────────────┴──────────────────┴─────────────┴────────┘

In [25]:
# Chaining two .filter() calls:
(
    penguins
    .filter(bill_length_mm='> 40')
    .filter(bill_length_mm='< 50')
    .sample(10)
)

shape: (10, 7)
┌───────────┬───────────┬────────────────┬───────────────┬──────────────────┬─────────────┬────────┐
│ species   ┆ island    ┆ bill_length_mm ┆ bill_depth_mm ┆ flipper_length_m ┆ body_mass_g ┆ sex    │
│ ---       ┆ ---       ┆ ---            ┆ ---           ┆ m                ┆ ---         ┆ ---    │
│ str       ┆ str       ┆ f64            ┆ f64           ┆ ---              ┆ f64         ┆ str    │
│           ┆           ┆                ┆               ┆ f64              ┆             ┆        │
╞═══════════╪═══════════╪════════════════╪═══════════════╪══════════════════╪═════════════╪════════╡
│ Adelie    ┆ Dream     ┆ 42.3           ┆ 21.2          ┆ 191.0            ┆ 4150.0      ┆ Male   │
│ Adelie    ┆ Torgersen ┆ 41.4           ┆ 18.5          ┆ 202.0            ┆ 3875.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 48.5           ┆ 17.5          ┆ 191.0            ┆ 3400.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 43.2           ┆ 16.6          ┆ 187.0            ┆ 2900.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 49.5           ┆ 19.0          ┆ 200.0            ┆ 3800.0      ┆ Male   │
│ Chinstrap ┆ Dream     ┆ 49.8           ┆ 17.3          ┆ 198.0            ┆ 3675.0      ┆ Female │
│ Chinstrap ┆ Dream     ┆ 45.7           ┆ 17.0          ┆ 195.0            ┆ 3650.0      ┆ Female │
│ Gentoo    ┆ Biscoe    ┆ 49.0           ┆ 16.1          ┆ 216.0            ┆ 5550.0      ┆ Male   │
│ Gentoo    ┆ Biscoe    ┆ 48.4           ┆ 16.3          ┆ 220.0            ┆ 5400.0      ┆ Male   │
│ Gentoo    ┆ Biscoe    ┆ 43.3           ┆ 14.0          ┆ 208.0            ┆ 4575.0      ┆ Female │
└───────────┴───────────┴────────────────┴───────────────┴──────────────────┴─────────────┴────────┘

## Helpful typo suggestions

If a column name is misspelled, `filter()` suggests close matches using fuzzy matching to help catch typos immediately.

In [26]:
# Intentional typo 'speceis' raises KeyError with a helpful suggestion
try:
    penguins.filter(speceis='Adelie')
except (KeyError, Exception) as exc:
    print("Caught expected error:", exc)

Caught expected error: unable to find column "speceis"; valid columns: ["species", "island", "bill_length_mm", "bill_depth_mm", "flipper_length_mm", "body_mass_g", "sex"]

Did you mean "species"?

## Real-world pipeline: filter → aggregate

In [27]:
# Tips: weekend dinner table of 2+, spending > $10 — average tip and bill by smoker status
# Using bracket notation [total bill] across qry and agg:
(
    tips
    .rename(columns={'total_bill': 'total bill'})
    .filter("[total bill] > 10", day=['Sat', 'Sun'], time='Dinner', size='>= 2')
    .by('smoker')
    .agg("tip = mean, [total bill] = mean, n = n")
)

shape: (2, 4)
┌────────┬──────────┬────────────┬─────┐
│ smoker ┆ tip      ┆ total bill ┆ n   │
│ ---    ┆ ---      ┆ ---        ┆ --- │
│ cat    ┆ f64      ┆ f64        ┆ i64 │
╞════════╪══════════╪════════════╪═════╡
│ No     ┆ 3.225464 ┆ 20.705876  ┆ 97  │
│ Yes    ┆ 3.087719 ┆ 23.232281  ┆ 57  │
└────────┴──────────┴────────────┴─────┘